[
 {
   "sno": 1,
   "name": "what is Binary Search Tree and what are its uses?",
   "ques_link": "",
   "video_link": "",
   "sol_link": ""
 },
 {
   "sno": 2,
   "name": "Intro to BST and why is BST useful ",
   "ques_link": "",
   "video_link": "",
   "sol_link": ""
 },
 {
   "sno": 3,
   "name": "We will be constructing BST from scratch using a sorted array",
   "ques_link": "",
   "video_link": "",
   "sol_link": ""
 },
 {
   "sno": 4,
   "name": "Talk about all the basic operations in BST and their respective time complexities",
   "ques_link": "",
   "video_link": "",
   "sol_link": ""
 },
 {
   "sno": 5,
   "name": "Make sure the students are clear with the fundamental operations of BST and their time complexities",
   "ques_link": "",
   "video_link": "",
   "sol_link": ""
 },
 {
   "sno": 6,
   "name": "Also state this fact that inorder traversal of BST gives keys in sorted order",
   "ques_link": "",
   "video_link": "",
   "sol_link": ""
 },
 {
   "sno": 7,
   "name": "Ask where you expect to find the smallest and largest value in BST?",
   "ques_link": "",
   "video_link": "",
   "sol_link": ""
 },
 {
   "sno": 8,
   "name": "contruct bst from sorted array using recursion ",
   "ques_link": "https://www.pepcoding.com/resources/online-java-foundation/binary-search-tree/size-sum-max-min-find-in-bst-official/ojquestion",
   "video_link": "",
   "sol_link": ""
 },
 {
   "sno": 9,
   "name": "Insert a node in a BST",
   "ques_link": "https://leetcode.com/problems/insert-into-a-binary-search-tree/",
   "video_link": "",
   "sol_link": ""
 },
 {
   "sno": 10,
   "name": "Delete Node in BST",
   "ques_link": "https://leetcode.com/problems/delete-node-in-a-bst/",
   "video_link": "",
   "sol_link": ""
 },
 {
   "sno": 11,
   "name": "validate BST",
   "ques_link": "https://leetcode.com/problems/validate-binary-search-tree/",
   "video_link": "",
   "sol_link": ""
 },
 {
   "sno": 12,
   "name": "LCA of BST",
   "ques_link": "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/",
   "video_link": "",
   "sol_link": ""
 },
 {
   "sno": 13,
   "name": "target sum pair",
   "ques_link": "https://leetcode.com/problems/two-sum-iv-input-is-a-bst/",
   "video_link": "",
   "sol_link": ""
 },
 {
   "sno": 14,
   "name": "Sum of range in BST",
   "ques_link": "https://leetcode.com/problems/range-sum-of-bst/",
   "video_link": "",
   "sol_link": ""
 },
 {
   "sno": 15,
   "name": "Minimum element in BST",
   "ques_link": "https://practice.geeksforgeeks.org/problems/minimum-element-in-bst",
   "video_link": "",
   "sol_link": ""
 },
 {
   "sno": 16,
   "name": "Search node in BST",
   "ques_link": "https://leetcode.com/problems/search-in-a-binary-search-tree/",
   "video_link": "",
   "sol_link": ""
 },
 {
   "sno": 17,
   "name": "Recover BST",
   "ques_link": "https://leetcode.com/problems/recover-binary-search-tree/",
   "video_link": "",
   "sol_link": ""
 },
 {
   "sno": 18,
   "name": "Construct Bst From Preorder Traversal",
   "ques_link": "",
   "video_link": "",
   "sol_link": ""
 },
 {
   "sno": 19,
   "name": "Construct Bst From postorder Traversal",
   "ques_link": "",
   "video_link": "",
   "sol_link": ""
 },
 {
   "sno": 20,
   "name": "Construct Bst From LevelOrderTraversal",
   "ques_link": "",
   "video_link": "",
   "sol_link": ""
 },
 {
   "sno": 21,
   "name": "BST iterator",
   "ques_link": "https://leetcode.com/problems/binary-search-tree-iterator/",
   "video_link": "",
   "sol_link": ""
 },
 {
   "sno": 22,
   "name": "Serialize and Deserialize BST",
   "ques_link": "https://leetcode.com/problems/serialize-and-deserialize-bst/",
   "video_link": "",
   "sol_link": ""
 },
 {
   "sno": 23,
   "name": "trim binary tree",
   "ques_link": "https://leetcode.com/problems/trim-a-binary-search-tree/",
   "video_link": "",
   "sol_link": ""
 },
 {
   "sno": 24,
   "name": "Two Sum IV - Input is a BST",
   "ques_link": "https://leetcode.com/problems/two-sum-iv-input-is-a-bst/",
   "video_link": "",
   "sol_link": ""
 }
]
